# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bridgefy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bridgefy

  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'Hero'
  pod 'SwiftMessages'

end
